name: Building Blocks
description: Learn the fundamental building blocks of Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello
        run: echo "Hello, World!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I will fail!"
          exit 1


      - name: SAy goodbye
        run: echo "Goodbye, World!"


    