name: Call Hello

on:
  workflow_dispatch:
    inputs:
      person:
        description: "Pe cine vrei să saluți?"
        required: true
        type: string
        default: "Donald"

jobs:
  call-hello:
    uses: ./.github/workflows/reusable-hello.yml
    with:
      person: ${{ inputs.person }}

  show-result:
    needs: call-hello
    runs-on: ubuntu-latest

    steps:
      - name: Display returned greeting
        env:
          GREETING: ${{ needs.call-hello.outputs.greeting }}
        run: |
           echo "Mesaj primit de la reutilizabil: $GREETING"
