name: Call Hello

on:
  workflow_dispatch:
    inputs:
      person:
        description: "Pe cine vrei să saluți?"
        required: true
        type: string
        default: "Donald"

jobs:
  call-hello:
    permissions: {}
    uses: ./.github/workflows/reusable-hello.yml
    with:
      person: ${{ inputs.person }}

  call-hello-again:
    permissions: {}
    uses: ./.github/workflows/reusable-hello.yml
    with:
      person: "Mickey Mouse"


  show-result:
    needs: [call-hello, call-hello-again]
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Display returned greeting
        env:
          GREETING: ${{ needs.call-hello.outputs.greeting }}
          GREETING2: ${{ needs.call-hello-again.outputs.greeting }}
        run: |
           echo "Mesaj primit de la reutilizabil: $GREETING"
           echo "Mesaj primit de la reutilizabil: $GREETING2"

      - name: List repository issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          gh issue list --repo "$REPOSITORY" --state all --limit 10
