name: Apelează salutul

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      person:
        description: Pe cine salutăm?
        required: true
        default: Donald
        type: string

permissions: {}
jobs:
  call-greeting:
    uses: ./.github/workflows/reusable-greeting.yml
    with:
      person: ${{ inputs.person || 'prietene' }}
    secrets:
      demo_token: ${{ secrets.DEMO_TOKEN }}
      