name: Permissions demo

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Creează un issue de exercițiu
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: "${{ github.repository }}"
      run: |
          gh issue create \
            --repo "$GH_REPO" \
            --title "Exercițiu permissions" \
            --body "Issue de test pentru lecția GitHub Actions."