name: Reusable Hello Workflow
on:
    workflow_call:
    
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
        - name: Say Hello
<<<<<<< HEAD
          run: 
            echo "Hello from the reusable workflow!"

=======
         run: echo "Hello from the reusable workflow!"
>>>>>>> 795152106dec558d95207ddd29714cbf737f6b3f



